-- Courses
ALTER SEQUENCE IF EXISTS "courses_id_seq" RESTART WITH 1;
INSERT INTO public."courses" (id, description, "name") VALUES( 1, 'Description Course #01', 'Course #01');
INSERT INTO public."courses" (id, description, "name") VALUES( 2, 'Description Course #02', 'Course #02');
INSERT INTO public."courses" (id, description, "name") VALUES( 3, 'Description Course #03', 'Course #03');
INSERT INTO public."courses" (id, description, "name") VALUES( 4, 'Description Course #04', 'Course #04');
INSERT INTO public."courses" (id, description, "name") VALUES( 5, 'Description Course #05', 'Course #05');
INSERT INTO public."courses" (id, description, "name") VALUES( 6, 'Description Course #06', 'Course #06');
INSERT INTO public."courses" (id, description, "name") VALUES( 7, 'Description Course #07', 'Course #07');
INSERT INTO public."courses" (id, description, "name") VALUES( 8, 'Description Course #08', 'Course #08');
INSERT INTO public."courses" (id, description, "name") VALUES( 9, 'Description Course #09', 'Course #09');
INSERT INTO public."courses" (id, description, "name") VALUES(10, 'Description Course #10', 'Course #10');
INSERT INTO public."courses" (id, description, "name") VALUES(11, 'Description Course #11', 'Course #11');
INSERT INTO public."courses" (id, description, "name") VALUES(12, 'Description Course #12', 'Course #12');
INSERT INTO public."courses" (id, description, "name") VALUES(13, 'Description Course #13', 'Course #13');
INSERT INTO public."courses" (id, description, "name") VALUES(14, 'Description Course #14', 'Course #14');
INSERT INTO public."courses" (id, description, "name") VALUES(15, 'Description Course #15', 'Course #15');
INSERT INTO public."courses" (id, description, "name") VALUES(16, 'Description Course #16', 'Course #16');
INSERT INTO public."courses" (id, description, "name") VALUES(17, 'Description Course #17', 'Course #17');
INSERT INTO public."courses" (id, description, "name") VALUES(18, 'Description Course #18', 'Course #18');
INSERT INTO public."courses" (id, description, "name") VALUES(19, 'Description Course #19', 'Course #19');
INSERT INTO public."courses" (id, description, "name") VALUES(20, 'Description Course #20', 'Course #20');
INSERT INTO public."courses" (id, description, "name") VALUES(21, 'Description Course #21', 'Course #21');
INSERT INTO public."courses" (id, description, "name") VALUES(22, 'Description Course #22', 'Course #22');
INSERT INTO public."courses" (id, description, "name") VALUES(23, 'Description Course #23', 'Course #23');
INSERT INTO public."courses" (id, description, "name") VALUES(24, 'Description Course #24', 'Course #24');
ALTER SEQUENCE IF EXISTS "courses_id_seq" RESTART WITH 101;
